version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "25432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: capital-features
      POSTGRES_USER: capital-features
      POSTGRES_PASSWORD: capital-features


volumes:
  pgsql_data:
    driver: local