version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "25432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: capital-features
      POSTGRES_USER: capital-features
      POSTGRES_PASSWORD: capital-features
  capital-features:
    image: jxch/capital-features:latest
    restart: unless-stopped
    ports:
      - "28080:8080"
    environment:
      PGSQL_DATASOURCE_URL: db
      DB_PASSWORD: capital-features
      DB_TABLE: capital-features
      DB_USERNAME: capital-features
      MAIL_USERNAME: xicheng_jiang@outlook.com
      MAIL_PASSWORD: xch_Jiang.outlook-A
      USERNAME: jxch
      PASSWORD: jxch
      GEMINI_KEY: AIzaSyCzLBBh243bcKndgYuByv9PUygjMEaTSJk


volumes:
  pgsql_data:
    driver: local