version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "15432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: capital-features
      POSTGRES_USER: capital-features
      POSTGRES_PASSWORD: capital-features
  capital-features:
    image: jxch/capital-features:latest
    restart: unless-stopped
    ports:
      - "18080:8080"
    environment:
      PGSQL_DATASOURCE_URL: db
      DB_PASSWORD: capital-features
      DB_TABLE: capital-features
      DB_USERNAME: capital-features
      MAIL_USERNAME: email@gmail.com
      MAIL_PASSWORD: email_password
      USERNAME: web_admin_username
      PASSWORD: web_admin_password
      GEMINI_KEY: gemini_api_key
      MINIO_URL: minio
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio


volumes:
  pgsql_data:
    driver: local