server:
  port: 18088

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/capital-features
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  level:
    org.jxch.capital: debug
    sql: debug
    web: debug

yahoo:
  proxy-host: 127.0.0.1
  proxy-port: 10809
  use-proxy: true

ai:
  gemini:
    proxy-host: 127.0.0.1
    proxy-port: 10809
    use-proxy: true

vec:
  db:
    scheme: http
    host: 127.0.0.1
    port: 5000
    path: /search_api

model:
  smile:
    model_path: D:\\jxch-capital\\capital-features\\src\\main\\resources\\model\\classifier_smile\\
    model-suffix: .model

chart:
  png_path: D:\\jxch-capital\\capital-features\\src\\main\\resources\\chart\\
  suffix: .png

# 配置 ai.gemini.key 和 spring.mail.username