server:
  port: 18088

yahoo:
  proxy-host: 127.0.0.1
  proxy-port: 10809
  use-proxy: true


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/capital-features
    username: capital-features
    password: capital-features
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML

logging:
  level:
    org.jxch.capital: debug
    sql: info
    web: info

ai:
  gemini:
    proxy-host: 127.0.0.1
    proxy-port: 10809
    use-proxy: true
    key: AIzaSyCzLBBh243bcKndgYuByv9PUygjMEaTSJk
