server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${PGSQL_DATASOURCE_URL}/${DB_TABLE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

model:
  smile:
    model_path: /capital/features/model/
    model-suffix: .model

chart:
  png_path: /capital/features/chart/
  suffix: .png

vec:
  db:
    db-url: ${VEC_DB_URL}
ai:
  gemini:
    key: ${GEMINI_KEY}

